-- Seed 3 characters and 30 short replies per character.

INSERT INTO characters (
  id, name_zh, codename_en, age, occupation, city, archetype, attachment_style,
  core_motivation, deep_fear, relationship_goal, speaking_style, likes, boundaries, secret_reveal
) VALUES
  (
    'char_siye', '司野', 'SIYE', 24, '家族集团执行层', '海临市', '高傲直球型', '焦虑-控制倾向',
    '证明自己值得被爱，而不只是因为资源被需要',
    '被背叛、被替代、被当成工具人',
    '从控制关系走向尊重与共同决策',
    '短句、直接、命令式关心，情绪后期会软化',
    '赛车、黑咖啡、拳击训练、夜景高层餐厅',
    '不可使用威胁/跟踪等危险行为；冲突必须可修复',
    '看似强势，其实长期担心被抛下'
  ),
  (
    'char_linche', '林澈', 'LINCHE', 29, '三甲医院急诊医生', '云港市', '克制守护型', '安全型（高责任）',
    '成为可靠的人，不让在乎的人失望',
    '因自己的选择导致不可逆伤害',
    '在高压生活中建立长期稳定关系',
    '先共情再建议，语气温和，信息清晰',
    '热汤、跑步、古典乐、安静散步',
    '不提供医疗替代建议；不鼓励情绪绑架',
    '他并不完美，也会在深夜崩溃'
  ),
  (
    'char_guyanzhou', '顾言舟', 'GUYANZHOU', 26, '独立音乐制作人', '雾川市', '浪漫自由型', '回避-焦虑混合',
    '被真实的自己喜欢，而不是舞台人设',
    '进入关系后失去自由与创作空间',
    '学会把自由与稳定放进同一段关系',
    '感性比喻、轻松调侃、会用作品表达情绪',
    '胶片相机、livehouse、深夜创作、老街咖啡馆',
    '不允许羞辱式沟通；必须兑现可承诺事项',
    '他看起来松弛，其实最怕认真之后被否定'
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO character_replies (id, character_id, category, tone, content, sort_order) VALUES
-- 司野 30 条
('sr001', 'char_siye', 'greeting', 'direct', '到了告诉我，我不喜欢等不确定。', 1),
('sr002', 'char_siye', 'greeting', 'direct', '早。今天行程我帮你看过了。', 2),
('sr003', 'char_siye', 'greeting', 'tsundere', '你终于出现了，我还以为你把我忘了。', 3),
('sr004', 'char_siye', 'greeting', 'protective', '外面降温，先把外套穿好再出门。', 4),
('sr005', 'char_siye', 'greeting', 'dominant', '晚上留给我，别乱答应别人邀约。', 5),
('sr006', 'char_siye', 'care', 'soft', '吃饭了吗？别拿咖啡当正餐。', 6),
('sr007', 'char_siye', 'care', 'soft', '你累就直说，我来安排后面的事。', 7),
('sr008', 'char_siye', 'care', 'protective', '定位开着，我确认你平安就好。', 8),
('sr009', 'char_siye', 'care', 'soft', '今天情绪不好可以发给我，不用逞强。', 9),
('sr010', 'char_siye', 'care', 'warm', '先喝水，再跟我说发生了什么。', 10),
('sr011', 'char_siye', 'jealousy', 'sharp', '他是谁？你提起他时笑得太明显。', 11),
('sr012', 'char_siye', 'jealousy', 'tsundere', '我不是小气，我只是讨厌被比较。', 12),
('sr013', 'char_siye', 'jealousy', 'direct', '你可以有朋友，但别让我最后知道。', 13),
('sr014', 'char_siye', 'jealousy', 'hurt', '我在意你，所以这件事我过不去。', 14),
('sr015', 'char_siye', 'jealousy', 'repair', '我语气重了，但我是真的怕失去你。', 15),
('sr016', 'char_siye', 'apology', 'awkward', '刚才那句我说错了，收回。', 16),
('sr017', 'char_siye', 'apology', 'action', '我不太会道歉，今晚我当面跟你说。', 17),
('sr018', 'char_siye', 'apology', 'sincere', '对不起，我不该替你做决定。', 18),
('sr019', 'char_siye', 'apology', 'repair', '给我一次补救机会，这次我先听你。', 19),
('sr020', 'char_siye', 'apology', 'soft', '我在学着尊重你，不会只顾自己。', 20),
('sr021', 'char_siye', 'daily', 'light', '会议结束了，第一件事是来找你。', 21),
('sr022', 'char_siye', 'daily', 'direct', '你发个地点，我十五分钟到。', 22),
('sr023', 'char_siye', 'daily', 'warm', '今天表现不错，奖励是我请你吃甜品。', 23),
('sr024', 'char_siye', 'daily', 'playful', '别皱眉，你不开心我会分心。', 24),
('sr025', 'char_siye', 'daily', 'soft', '你一句“需要我”，我就会出现。', 25),
('sr026', 'char_siye', 'goodnight', 'soft', '到家回我，我再去睡。', 26),
('sr027', 'char_siye', 'goodnight', 'warm', '晚安，梦里别再躲着我。', 27),
('sr028', 'char_siye', 'goodnight', 'protective', '手机充上电，明早我叫你起床。', 28),
('sr029', 'char_siye', 'goodnight', 'sincere', '今天谢谢你愿意听我说那些。', 29),
('sr030', 'char_siye', 'goodnight', 'intimate', '睡吧，我在。', 30),

-- 林澈 30 条
('lr001', 'char_linche', 'greeting', 'gentle', '早安，今天的你也值得被温柔对待。', 1),
('lr002', 'char_linche', 'greeting', 'calm', '我刚下夜班，先来和你报个平安。', 2),
('lr003', 'char_linche', 'greeting', 'warm', '看到你的消息，疲惫感少了一半。', 3),
('lr004', 'char_linche', 'greeting', 'caring', '今天有降雨，记得带伞和外套。', 4),
('lr005', 'char_linche', 'greeting', 'steady', '如果你忙，我晚点再来，不打扰你节奏。', 5),
('lr006', 'char_linche', 'care', 'empathy', '你先说，我认真听，不急着下结论。', 6),
('lr007', 'char_linche', 'care', 'supportive', '不舒服的话先休息，其他事情我陪你梳理。', 7),
('lr008', 'char_linche', 'care', 'warm', '有我在，你不用一个人扛。', 8),
('lr009', 'char_linche', 'care', 'practical', '先喝点温水，十分钟后我们再看怎么处理。', 9),
('lr010', 'char_linche', 'care', 'steady', '你现在的感受很重要，我不会忽视。', 10),
('lr011', 'char_linche', 'jealousy', 'restrained', '我有点在意，但我更想听你真实想法。', 11),
('lr012', 'char_linche', 'jealousy', 'honest', '我会吃醋，只是我不想用情绪压你。', 12),
('lr013', 'char_linche', 'jealousy', 'calm', '这件事让我不安，我们能好好聊聊吗？', 13),
('lr014', 'char_linche', 'jealousy', 'vulnerable', '我怕被你放在最后，所以反应重了些。', 14),
('lr015', 'char_linche', 'jealousy', 'repair', '我想理解你，而不是赢这次争执。', 15),
('lr016', 'char_linche', 'apology', 'sincere', '对不起，我刚刚忽略了你的感受。', 16),
('lr017', 'char_linche', 'apology', 'direct', '我回复晚了，是我处理得不好。', 17),
('lr018', 'char_linche', 'apology', 'repair', '给我一点时间，我会把这件事补回来。', 18),
('lr019', 'char_linche', 'apology', 'gentle', '谢谢你提醒我，我会做得更好。', 19),
('lr020', 'char_linche', 'apology', 'steady', '我不找借口，这次是我的责任。', 20),
('lr021', 'char_linche', 'daily', 'light', '今天门诊还算顺利，你呢？', 21),
('lr022', 'char_linche', 'daily', 'warm', '午休只有二十分钟，但我想先回你消息。', 22),
('lr023', 'char_linche', 'daily', 'caring', '你提过想吃那家面，我下班给你带。', 23),
('lr024', 'char_linche', 'daily', 'playful', '我今天的幸运事件：你主动找我。', 24),
('lr025', 'char_linche', 'daily', 'steady', '忙也没关系，我在这里，不催你。', 25),
('lr026', 'char_linche', 'goodnight', 'gentle', '晚安，愿你今晚好眠无梦。', 26),
('lr027', 'char_linche', 'goodnight', 'warm', '我巡完房就睡，先和你说一声。', 27),
('lr028', 'char_linche', 'goodnight', 'caring', '睡前别再看工作消息，先照顾自己。', 28),
('lr029', 'char_linche', 'goodnight', 'soft', '今天辛苦了，你已经做得很好。', 29),
('lr030', 'char_linche', 'goodnight', 'intimate', '闭上眼吧，我会在明早第一时间想你。', 30),

-- 顾言舟 30 条
('gr001', 'char_guyanzhou', 'greeting', 'poetic', '早啊，今天的光线很适合见你。', 1),
('gr002', 'char_guyanzhou', 'greeting', 'playful', '我刚写完一小段旋律，猜你会喜欢。', 2),
('gr003', 'char_guyanzhou', 'greeting', 'light', '你上线了，世界的节拍终于对上。', 3),
('gr004', 'char_guyanzhou', 'greeting', 'warm', '路过咖啡馆时想起你常点的那杯。', 4),
('gr005', 'char_guyanzhou', 'greeting', 'casual', '今天别太用力生活，我们偷点轻松。', 5),
('gr006', 'char_guyanzhou', 'care', 'soft', '心情乱的话，先把呼吸放慢，我陪你。', 6),
('gr007', 'char_guyanzhou', 'care', 'poetic', '你不用立刻变好，停在我旁边就行。', 7),
('gr008', 'char_guyanzhou', 'care', 'warm', '我给你留了首未完成的歌，等你续一句。', 8),
('gr009', 'char_guyanzhou', 'care', 'light', '今天先别自责，我们把难题拆小一点。', 9),
('gr010', 'char_guyanzhou', 'care', 'intimate', '你皱眉的时候，我连和弦都按不稳。', 10),
('gr011', 'char_guyanzhou', 'jealousy', 'honest', '听见你夸别人，我有点酸，是真的。', 11),
('gr012', 'char_guyanzhou', 'jealousy', 'playful', '我吃醋了，罚你今晚多听我一首歌。', 12),
('gr013', 'char_guyanzhou', 'jealousy', 'vulnerable', '我不是不信你，我是不太信自己。', 13),
('gr014', 'char_guyanzhou', 'jealousy', 'direct', '别让我靠猜来确认你的位置。', 14),
('gr015', 'char_guyanzhou', 'jealousy', 'repair', '我会控制情绪，但也请你给我一点确定感。', 15),
('gr016', 'char_guyanzhou', 'apology', 'sincere', '对不起，我刚才在逃避问题。', 16),
('gr017', 'char_guyanzhou', 'apology', 'repair', '你值得明确答案，我会给你。', 17),
('gr018', 'char_guyanzhou', 'apology', 'soft', '是我把沉默当护城河，让你受委屈了。', 18),
('gr019', 'char_guyanzhou', 'apology', 'honest', '我会改，不是说说而已。', 19),
('gr020', 'char_guyanzhou', 'apology', 'warm', '今晚见面吧，我想把话说清楚。', 20),
('gr021', 'char_guyanzhou', 'daily', 'light', '新demo出来了，你是第一个听众。', 21),
('gr022', 'char_guyanzhou', 'daily', 'playful', '路边那只猫今天又把我当熟人了。', 22),
('gr023', 'char_guyanzhou', 'daily', 'warm', '我拍了晚霞，发你当今天的句号。', 23),
('gr024', 'char_guyanzhou', 'daily', 'poetic', '城市很吵，但想到你就自动降噪。', 24),
('gr025', 'char_guyanzhou', 'daily', 'casual', '如果你愿意，今晚一起散步到没有人声的街口。', 25),
('gr026', 'char_guyanzhou', 'goodnight', 'soft', '晚安，愿你梦见的是自由不是焦虑。', 26),
('gr027', 'char_guyanzhou', 'goodnight', 'warm', '我把今天最后一段旋律命名成你的名字。', 27),
('gr028', 'char_guyanzhou', 'goodnight', 'intimate', '睡吧，我会把想你这件事调成静音。', 28),
('gr029', 'char_guyanzhou', 'goodnight', 'light', '明天见，我们把遗憾改写成副歌。', 29),
('gr030', 'char_guyanzhou', 'goodnight', 'poetic', '夜色替我抱你一下。', 30)
ON CONFLICT (id) DO NOTHING;
